version: '2.2'
services:
  backend:
    build:
      context: .  
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]  
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80" 
    volumes:
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./conf/backend.vhost.conf:/usr/local/apache2/conf/vhosts/backend.vhost.conf
    depends_on:
      - backend  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"] 
      interval: 30s
      timeout: 10s
      retries: 5
